### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by noclat** [noclat/scss-starter#1]
- [ ] Update breakpoints doc with default breakpoints values
- [ ] Add “order” helpers in the grid
- [ ] Document grid options (vertical alignment and horizontal distribution)
- [ ] Rewrite and expand FAQ
- [ ] Get feedback on the FAQ
